<?php
/**
 * Created by PhpStorm.
 * User: Andrew
 * Date: 27.01.2017
 * Time: 23:22
 */

namespace App\Controllers;


use App\Controller;
use App\Models\Article;

class News
    extends Controller
{
    public function actionAll()
    {
        $this->view->news = Article::findLast(3);
        echo $this->view->render(__DIR__ . '/../Templates/index.php');
    }

    protected function access(): bool
    {
        return parent::access(); // TODO
    }

    protected function beforeAction()
    {
        parent::beforeAction(); // TODO: Change the autogenerated stub
    }

    public function actionOne($id = null)
    {
        $this->view->article = \App\Models\Article::findById($id);
        echo $this->view->render(__DIR__ . '/../Templates/article.php');
    }

}